name: CI
on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: setup gradle
        uses: gradle/gradle-build-action@v3
      - name: ensure gradle wrapper is executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: upload code coverage report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/reports/jacoco/test/jacocoTestReport.xml
          slug: SaimonWoidig/payment-system
